---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: vbox/bionic64-php
    driver:
      box: bionic64-php
      provider: virtualbox

verifier:
  name: inspec

suites:
  - name: default
